// pages/admin/users.tsx
// ---------------------------------------------------------------------------
// Admin‑only user‑role management panel for Latimere Host OS
//  • Lists every UserProfile row (username‑key only)
//  • Lets an admin promote/demote by clicking a role button
//  • Uses an in‑file GraphQL query for listUserProfiles so we’re not blocked
//    if the generated operation is missing.
//  • Wrapped with withRole(['admin']) so only admins can access it.
//  • Console logs for every network action make troubleshooting easy.
// ---------------------------------------------------------------------------

import { useEffect, useState } from 'react';
import { generateClient } from 'aws-amplify/api';

// Generated by Amplify codegen (update path if yours is different)
// Path tweaked back to match tsconfig alias
import { updateUserProfile } from '@/graphql/mutations';

import type { UserProfile } from '@/types/UserProfile';
import { withRole } from '@/components/withRole';
import Layout       from '@/components/Layout';

const client = generateClient({ authMode: 'userPool' });

// Inline query in case listUserProfiles wasn’t generated yet
const LIST_USER_PROFILES = /* GraphQL */ `
  query ListUserProfiles {
    listUserProfiles {
      items {
        id
        username
        role
        hasPaid
        owner
      }
    }
  }
`;

function UsersAdminPage() {
  const [users, setUsers] = useState<UserProfile[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // ── Fetch all profiles ───────────────────────────────────────────────
  useEffect(() => {
    (async () => {
      console.log('[UsersAdmin] fetching user profiles…');
      try {
        const res: any = await client.graphql({ query: LIST_USER_PROFILES });
        const items: UserProfile[] = res?.data?.listUserProfiles?.items ?? [];
        console.log(`[UsersAdmin] received ${items.length} profiles`, items);
        setUsers(items);
      } catch (err) {
        console.error('❌ [UsersAdmin] listUserProfiles error:', err);
        setError('Failed to load users.');
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  // ── Role update helper ───────────────────────────────────────────────
  const setRole = async (id: string, role: 'admin' | 'owner' | 'cleaner') => {
    console.log(`[UsersAdmin] setting role for ${id} → ${role}`);
    try {
      await client.graphql({
        query: updateUserProfile,
        variables: { input: { id, role } },
      });
      setUsers((prev) => prev.map((u) => (u.id === id ? { ...u, role } : u)));
      console.log('[UsersAdmin] role updated ✓');
    } catch (err) {
      console.error('❌ [UsersAdmin] updateUserProfile error:', err);
      alert('Role update failed – check console for details.');
    }
  };

  // ── Render ───────────────────────────────────────────────────────────
  return (
    <Layout title="User Management">
      <div className="max-w-4xl mx-auto p-6">
        <h1 className="text-3xl font-bold mb-6">User Roles</h1>

        {loading && <p>Loading users…</p>}
        {error && <p className="text-red-600">{error}</p>}

        {!loading && !error && (
          <table className="w-full border text-sm">
            <thead>
              <tr className="bg-gray-100 text-left">
                <th className="p-2">Username</th>
                <th className="p-2 text-center">Current role</th>
                <th className="p-2 text-center">Change role</th>
              </tr>
            </thead>
            <tbody>
              {users.map((u) => (
                <tr key={u.id} className="border-t">
                  <td className="p-2 break-words">{u.username}</td>
                  <td className="p-2 text-center font-medium">{u.role}</td>
                  <td className="p-2 text-center space-x-2">
                    {(['admin', 'owner', 'cleaner'] as const).map((r) => (
                      <button
                        key={r}
                        disabled={u.role === r}
                        onClick={() => setRole(u.id, r)}
                        className={`px-2 py-1 rounded shadow text-xs disabled:opacity-40 ${
                          u.role === r
                            ? 'bg-blue-500 text-white'
                            : 'bg-gray-200 hover:bg-gray-300'
                        }`}
                      >
                        {r}
                      </button>
                    ))}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </Layout>
  );
}

// Guard the page — only Admins may manage roles
export default withRole(['admin'])(UsersAdminPage);
