import '@/styles/globals.css';       // or wherever your global CSS lives
import type { AppProps } from 'next/app';
import { Amplify } from 'aws-amplify';
import awsExports from '@/aws-exports';   // this file is auto-generated by Amplify CLI

Amplify.configure(awsExports);

export default function App({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />;
}

