import '../styles/globals.css';
import type { AppProps } from 'next/app';
import { Amplify } from 'aws-amplify';
import { Authenticator } from '@aws-amplify/ui-react';
import awsExports from '../aws-exports'; // auto‑generated by Amplify CLI

Amplify.configure(awsExports);

export default function App({ Component, pageProps }: AppProps) {
  return (
    <Authenticator>
      <nav style={{ display: 'flex', gap: '1rem', marginBottom: '1.5rem' }}>
        <a href="/">Home</a>
        <a href="/properties">Properties</a>
        <a href="/units">Units</a>
      </nav>
      <Component {...pageProps} />
    </Authenticator>
  );
}

